name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o hashpass-windows-amd64.exe .

      - name: Build Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o hashpass-linux-amd64 .

      - name: Build macOS amd64
        run: GOOS=darwin GOARCH=amd64 go build -o hashpass-macos-amd64 .

      - name: Get commit SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.vars.outputs.sha }}
          name: Build ${{ steps.vars.outputs.sha }}
          files: |
            hashpass-windows-amd64.exe
            hashpass-linux-amd64
            hashpass-macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}